---
bungeecord:
  restart: always
  ports:
    - "0.0.0.0:25577:25577"
  links:
    - spigot:spigot

spigot:
  environment:
    - MINECRAFT_VERSION=latest
    - DEFAULT_OP=Toonsev
    - MINECRAFT_EULA=true
  restart: always
  links:
    - spigot_db:spigot_db

spigot_db:
  restart: always
